enum Pattern {
    Badge = 'Badge',
    Breadcrumb = 'Breadcrumb',
    ButtonWithIcon = 'Button with icon',
    Card = 'Card',
    Centering = 'Centering',
    DockedAtCorner = 'Docked at corner',
    DotNavigation = 'Dot navigation',
    FeatureList = 'Feature list',
    FixedAtCorner = 'Fixed at corner',
    HolyGrail = 'Holy grail',
    InputAddOn = 'Input add-on',
    MediaObject = 'Media object',
    Menu = 'Menu',
    Modal = 'Modal',
    Notification = 'Notification',
    Pagination = 'Pagination',
    PreviousNextButtons = 'Previous next buttons',
    PricingTable = 'Pricing table',
    PropertyList = 'Property list',
    ProgressBar = 'Progress bar',
    QuestionsAndAnswers = 'Questions and answers',
    RadioSwitch = 'Radio switch',
    SameHeightColumns = 'Same height columns',
    SearchBox = 'Search box',
    Separator = 'Separator',
    Sidebar = 'Sidebar',
    SimpleGrid = 'Simple grid',
    Slider = 'Slider',
    SpinButton = 'Spin button',
    SplitNavigation = 'Split navigation',
    SplitScreen = 'Split screen',
    StepperInput = 'Stepper input',
    StickyFooter = 'Sticky footer',
    StickyHeader = 'Sticky header',
    Switch = 'Switch',
    Tab = 'Tab',
    TogglePasswordVisibility = 'Toggle password visibility',
    Wizard = 'Wizard',
}

export default Pattern;
